### ISSUE TITLE
Draw 'IKEA' style instructions

### ISSUE THREAD

**Issue by yustarandomname** [PRIME-TU-Delft/lavaflow#23]
Draw ['Ikea'](https://miro.medium.com/v2/resize:fit:720/format:webp/1*KmJbC8bdTxvCSQdyxGtxaA.jpeg) style instructions for the  following places of the application:

- [x] Drawing instructions
- [x] Scanning instructions
- [x] Marker selection instructions
- [x] Turbine placement

(Bonus) improve text for all instructions (these have been written in quite a hurry without proper consideration of the current app)

**Comment by PHengst** [comment]
- [ ] place images in instruction pages

**Comment by PHengst** [comment]
is placement in AR also necceary?
